import {
  Employee,
  AttendanceRecord,
  LeaveRequest,
  Payroll,
  Evaluation,
  HRTask,
  NotificationItem,
  AuditLog,
  AccountingJournalEntry,
  CompanyBranding,
  ChatGroup,
  ChatMessage,
  AccessRequest
} from '../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-admin',
    employeeCode: 'EMP-EG-001',
    fullName: 'محمد زكريا (المدير الإداري ومسؤول الموارد البشرية)',
    email: 'mz0970mmz@gmail.com',
    phone: '+20 10 1234 5678',
    department: 'الموارد البشرية والإدارة العليا',
    jobTitle: 'مدير عام الموارد البشرية والشؤون الإدارية (HR Director)',
    basicSalary: 38000,
    housingAllowance: 6000,
    transportAllowance: 3000,
    otherAllowances: 2500,
    hireDate: '2021-01-15',
    status: 'active',
    nationalId: '29201010101234',
    socialInsuranceNumber: '109847291',
    iban: 'EG380002000100000012345678901',
    contractType: 'unlimited',
    contractStartDate: '2021-01-15',
    insuranceJoinDate: '2021-01-15',
    insuranceRenewalDate: '2027-01-01',
    insuranceFormStatus: 'form2_submitted',
    insuranceSalary: 14500,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    remainingLeaveDays: 28,
    casualLeaveDays: 6,
  },
  {
    id: 'emp-1',
    employeeCode: 'EMP-EG-002',
    fullName: 'م. أحمد محمود الشناوي',
    email: 'ahmed.shinawy@company.eg',
    phone: '+20 11 2345 6789',
    department: 'الهندسة والتقنية',
    jobTitle: 'كبير مهندسي البرمجيات والنظم السحابية',
    basicSalary: 32000,
    housingAllowance: 4000,
    transportAllowance: 2500,
    otherAllowances: 1500,
    hireDate: '2022-03-01',
    status: 'active',
    nationalId: '29405120102345',
    socialInsuranceNumber: '112093842',
    iban: 'EG450003000100000023456789012',
    contractType: 'fixed',
    contractStartDate: '2024-10-15',
    contractEndDate: '2026-10-15', // ينتهي خلال 20 يوماً
    insuranceJoinDate: '2022-03-01',
    insuranceRenewalDate: '2026-10-10', // تجديد استمارة 2 السنوية مستحق
    insuranceFormStatus: 'form2_pending_annual',
    insuranceSalary: 14500,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    remainingLeaveDays: 21,
    casualLeaveDays: 5,
  },
  {
    id: 'emp-2',
    employeeCode: 'EMP-EG-003',
    fullName: 'سارة عبد المنعم الصاوي',
    email: 'sarah.elsawy@company.eg',
    phone: '+20 12 3456 7890',
    department: 'الموارد البشرية',
    jobTitle: 'أخصائية أولى علاقات العمل والامتثال القانوني',
    basicSalary: 22000,
    housingAllowance: 3000,
    transportAllowance: 1500,
    otherAllowances: 1000,
    hireDate: '2023-01-10',
    status: 'active',
    nationalId: '29608140103456',
    socialInsuranceNumber: '115829104',
    iban: 'EG780004000100000034567890123',
    contractType: 'fixed',
    contractStartDate: '2024-11-10',
    contractEndDate: '2026-11-10', // ينتهي خلال 46 يوماً
    insuranceJoinDate: '2023-01-10',
    insuranceRenewalDate: '2027-01-01',
    insuranceFormStatus: 'form2_submitted',
    insuranceSalary: 14500,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    remainingLeaveDays: 19,
    casualLeaveDays: 4,
  },
  {
    id: 'emp-3',
    employeeCode: 'EMP-EG-004',
    fullName: 'عبد الرحمن شريف الألفي',
    email: 'abdelrahman.elalfy@company.eg',
    phone: '+20 15 4567 8901',
    department: 'المالية والمحاسبة',
    jobTitle: 'رئيس قسم الحسابات والضرائب العامة',
    basicSalary: 26000,
    housingAllowance: 3500,
    transportAllowance: 2000,
    otherAllowances: 1200,
    hireDate: '2022-08-15',
    status: 'active',
    nationalId: '29302190104567',
    socialInsuranceNumber: '118492015',
    iban: 'EG910005000100000045678901234',
    contractType: 'fixed',
    contractStartDate: '2024-09-30',
    contractEndDate: '2026-09-30', // ينتهي خلال 5 أيام (عاجل جداً!)
    insuranceJoinDate: '2022-08-15',
    insuranceRenewalDate: '2026-10-01', // تجديد استمارة 2 مستحق
    insuranceFormStatus: 'form2_pending_annual',
    insuranceSalary: 14500,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    remainingLeaveDays: 16,
    casualLeaveDays: 5,
  },
  {
    id: 'emp-4',
    employeeCode: 'EMP-EG-005',
    fullName: 'نورهان طارق إبراهيم',
    email: 'nourhan.tarek@company.eg',
    phone: '+20 10 9876 5432',
    department: 'التسويق والمبيعات',
    jobTitle: 'مسؤولة الحملات التسويقية والاتصال المؤسسي',
    basicSalary: 18000,
    housingAllowance: 2500,
    transportAllowance: 1500,
    otherAllowances: 1000,
    hireDate: '2024-02-01',
    status: 'active',
    nationalId: '29811250105678',
    socialInsuranceNumber: '121938475',
    iban: 'EG120006000100000056789012345',
    contractType: 'fixed',
    contractStartDate: '2024-02-01',
    contractEndDate: '2027-02-01',
    insuranceJoinDate: '2024-02-01',
    insuranceRenewalDate: '2026-10-25', // موعد مراجعة الاشتراك
    insuranceFormStatus: 'form1_completed',
    insuranceSalary: 14500,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    remainingLeaveDays: 24,
    casualLeaveDays: 7,
  },
  {
    id: 'emp-5',
    employeeCode: 'EMP-EG-006',
    fullName: 'كريم حسن الجوهري',
    email: 'karim.elgohary@company.eg',
    phone: '+20 11 8765 4321',
    department: 'العمليات التشغيلية',
    jobTitle: 'مشرف سلاسل الإمداد ومراقبة الجودة',
    basicSalary: 20000,
    housingAllowance: 2500,
    transportAllowance: 1500,
    otherAllowances: 800,
    hireDate: '2023-06-15',
    status: 'on_leave',
    nationalId: '29509300106789',
    socialInsuranceNumber: '124859203',
    iban: 'EG330007000100000067890123456',
    contractType: 'fixed',
    contractStartDate: '2025-06-15',
    contractEndDate: '2026-12-15',
    insuranceJoinDate: '2023-06-15',
    insuranceRenewalDate: '2027-01-01',
    insuranceFormStatus: 'form2_submitted',
    insuranceSalary: 14500,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    remainingLeaveDays: 14,
    casualLeaveDays: 3,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-admin',
    employeeId: 'emp-admin',
    employeeName: 'محمد زكريا (المدير الإداري ومسؤول الموارد البشرية)',
    department: 'الموارد البشرية والإدارة العليا',
    date: '2026-09-24',
    checkInTime: '08:00:00',
    checkOutTime: '17:10:00',
    workHours: 8.2,
    overtimeHours: 0.2,
    status: 'present',
    location: 'المقر الرئيسي - التجمع الخامس، القاهرة',
    notes: 'حضور منتظم في الموعد ومطابق لنطاق GPS',
  },
  {
    id: 'att-1',
    employeeId: 'emp-1',
    employeeName: 'م. أحمد محمود الشناوي',
    department: 'الهندسة والتقنية',
    date: '2026-09-24',
    checkInTime: '08:05:14',
    checkOutTime: '17:35:00',
    workHours: 8.5,
    overtimeHours: 0.5,
    status: 'present',
    location: 'المقر الرئيسي - التجمع الخامس، القاهرة',
    notes: 'ساعات عمل إضافية معتمدة بمعدل 135% نهاري',
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    employeeName: 'سارة عبد المنعم الصاوي',
    department: 'الموارد البشرية',
    date: '2026-09-24',
    checkInTime: '08:12:00',
    checkOutTime: '17:00:00',
    workHours: 8.0,
    overtimeHours: 0,
    status: 'present',
    location: 'المقر الرئيسي - التجمع الخامس، القاهرة',
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    employeeName: 'عبد الرحمن شريف الألفي',
    department: 'المالية والمحاسبة',
    date: '2026-09-24',
    checkInTime: '08:35:00',
    checkOutTime: '17:30:00',
    workHours: 7.9,
    overtimeHours: 0,
    status: 'late',
    location: 'المقر الرئيسي - التجمع الخامس، القاهرة',
    notes: 'تأخير 20 دقيقة بسبب زحام الطريق الدائري',
  },
  {
    id: 'att-4',
    employeeId: 'emp-4',
    employeeName: 'نورهان طارق إبراهيم',
    department: 'التسويق والمبيعات',
    date: '2026-09-24',
    checkInTime: '07:50:00',
    checkOutTime: '18:00:00',
    workHours: 9.2,
    overtimeHours: 1.2,
    status: 'present',
    location: 'فرع القرية الذكية - 6 أكتوبر / الجيزة',
    notes: 'إضافي لتغطية إطلاق المعرض التسويقي',
  },
  {
    id: 'att-5',
    employeeId: 'emp-5',
    employeeName: 'كريم حسن الجوهري',
    department: 'العمليات التشغيلية',
    date: '2026-09-24',
    workHours: 0,
    overtimeHours: 0,
    status: 'leave',
    notes: 'إجازة اعتيادية سنوية طبقاً للمادة (47) من قانون العمل المصري',
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'leave-1',
    employeeId: 'emp-5',
    employeeName: 'كريم حسن الجوهري',
    department: 'العمليات التشغيلية',
    leaveType: 'annual',
    startDate: '2026-09-20',
    endDate: '2026-09-26',
    days: 6,
    reason: 'إجازة سنوية اعتيادية متصلة',
    status: 'approved',
    actionNotes: 'معتمد بعد تسليم العهدة وجدول تسليم شحنات العمليات',
    reviewedBy: 'محمد زكريا (المدير الإداري)',
    createdAt: '2026-09-12',
  },
  {
    id: 'leave-2',
    employeeId: 'emp-3',
    employeeName: 'عبد الرحمن شريف الألفي',
    department: 'المالية والمحاسبة',
    leaveType: 'casual',
    startDate: '2026-09-27',
    endDate: '2026-09-28',
    days: 2,
    reason: 'إجازة عارضة لظرف عائلي طارئ بالإسكندرية (المادة 48 من قانون العمل)',
    status: 'pending',
    createdAt: '2026-09-23',
  },
  {
    id: 'leave-3',
    employeeId: 'emp-4',
    employeeName: 'نورهان طارق إبراهيم',
    department: 'التسويق والمبيعات',
    leaveType: 'sick',
    startDate: '2026-09-15',
    endDate: '2026-09-16',
    days: 2,
    reason: 'وعكة صحية طارئة مع تقرير من مستشفى دار الفؤاد',
    status: 'approved',
    actionNotes: 'معتمد بموجب التقرير الطبي المرفق وفقاً للائحة التأمين الصحي',
    reviewedBy: 'سارة الصاوي',
    createdAt: '2026-09-15',
  },
];

export const INITIAL_PAYROLLS: Payroll[] = [
  {
    id: 'pay-admin',
    month: '2026-09',
    employeeId: 'emp-admin',
    employeeName: 'محمد زكريا (المدير الإداري ومسؤول الموارد البشرية)',
    department: 'الموارد البشرية والإدارة العليا',
    jobTitle: 'مدير عام الموارد البشرية والشؤون الإدارية (HR Director)',
    basicSalary: 38000,
    housingAllowance: 6000,
    transportAllowance: 3000,
    overtimePay: 0,
    bonus: 3000,
    socialInsuranceEmployee: 1540, // 11% من الحد التأميني (أجر الاشتراك التأميني الشامل)
    socialInsuranceEmployer: 2625, // 18.75%
    gosiDeduction: 1540,
    incomeTaxDeduction: 4250, // ضريبة كسب العمل المصرية وفقاً للشرائح التصاعدية
    martyrsFundDeduction: 25,
    absenceDeduction: 0,
    otherDeductions: 0,
    netSalary: 44185,
    status: 'approved',
    paymentMethod: 'تحويل بنكي فوري (CIB / البنك التجاري الدولي - مصر)',
    notes: 'مسير شهر سبتمبر 2026 - قطاع الإدارة التنفيذية',
    createdAt: '2026-09-22',
  },
  {
    id: 'pay-1',
    month: '2026-09',
    employeeId: 'emp-1',
    employeeName: 'م. أحمد محمود الشناوي',
    department: 'الهندسة والتقنية',
    jobTitle: 'كبير مهندسي البرمجيات والنظم السحابية',
    basicSalary: 32000,
    housingAllowance: 4000,
    transportAllowance: 2500,
    overtimePay: 950,
    bonus: 2000,
    socialInsuranceEmployee: 1540, // 11%
    socialInsuranceEmployer: 2625, // 18.75%
    gosiDeduction: 1540,
    incomeTaxDeduction: 3400,
    martyrsFundDeduction: 20,
    absenceDeduction: 0,
    otherDeductions: 0,
    netSalary: 36490,
    status: 'approved',
    paymentMethod: 'تحويل بنكي عبر شبكة المدفوعات اللحظية (InstaPay / البنك الأهلي المصري)',
    notes: 'إضافي ساعات عمل ليلية بنسبة 170% طبقاً للمادة 85 من قانون العمل',
    createdAt: '2026-09-22',
  },
  {
    id: 'pay-2',
    month: '2026-09',
    employeeId: 'emp-2',
    employeeName: 'سارة عبد المنعم الصاوي',
    department: 'الموارد البشرية',
    jobTitle: 'أخصائية أولى علاقات العمل والامتثال القانوني',
    basicSalary: 22000,
    housingAllowance: 3000,
    transportAllowance: 1500,
    overtimePay: 0,
    bonus: 1500,
    socialInsuranceEmployee: 1540,
    socialInsuranceEmployer: 2625,
    gosiDeduction: 1540,
    incomeTaxDeduction: 1850,
    martyrsFundDeduction: 15,
    absenceDeduction: 0,
    otherDeductions: 0,
    netSalary: 24595,
    status: 'approved',
    paymentMethod: 'تحويل بنكي فوري (بنك مصر - Banque Misr)',
    notes: 'مسير شهر سبتمبر 2026 مع حافز التميز الإداري',
    createdAt: '2026-09-22',
  },
  {
    id: 'pay-3',
    month: '2026-09',
    employeeId: 'emp-3',
    employeeName: 'عبد الرحمن شريف الألفي',
    department: 'المالية والمحاسبة',
    jobTitle: 'رئيس قسم الحسابات والضرائب العامة',
    basicSalary: 26000,
    housingAllowance: 3500,
    transportAllowance: 2000,
    overtimePay: 0,
    bonus: 1000,
    socialInsuranceEmployee: 1540,
    socialInsuranceEmployer: 2625,
    gosiDeduction: 1540,
    incomeTaxDeduction: 2350,
    martyrsFundDeduction: 18,
    absenceDeduction: 250, // خصم تأخير
    otherDeductions: 0,
    netSalary: 28342,
    status: 'approved',
    paymentMethod: 'تحويل بنكي فوري (CIB / البنك التجاري الدولي)',
    notes: 'خصم تأخير ساعتين وفقاً للائحة الجزاءات المعتمدة من مكتب العمل',
    createdAt: '2026-09-22',
  },
  {
    id: 'pay-4',
    month: '2026-09',
    employeeId: 'emp-4',
    employeeName: 'نورهان طارق إبراهيم',
    department: 'التسويق والمبيعات',
    jobTitle: 'مسؤولة الحملات التسويقية والاتصال المؤسسي',
    basicSalary: 18000,
    housingAllowance: 2500,
    transportAllowance: 1500,
    overtimePay: 600,
    bonus: 1200,
    socialInsuranceEmployee: 1540,
    socialInsuranceEmployer: 2625,
    gosiDeduction: 1540,
    incomeTaxDeduction: 1280,
    martyrsFundDeduction: 12,
    absenceDeduction: 0,
    otherDeductions: 0,
    netSalary: 22468,
    status: 'approved',
    paymentMethod: 'تحويل بنكي فوري (بنك QNB الأهلي مصر)',
    notes: 'مكافأة نجاح الحملة الترويجية للربع الثالث',
    createdAt: '2026-09-22',
  },
  {
    id: 'pay-5',
    month: '2026-09',
    employeeId: 'emp-5',
    employeeName: 'كريم حسن الجوهري',
    department: 'العمليات التشغيلية',
    jobTitle: 'مشرف سلاسل الإمداد ومراقبة الجودة',
    basicSalary: 20000,
    housingAllowance: 2500,
    transportAllowance: 1500,
    overtimePay: 0,
    bonus: 0,
    socialInsuranceEmployee: 1540,
    socialInsuranceEmployer: 2625,
    gosiDeduction: 1540,
    incomeTaxDeduction: 1550,
    martyrsFundDeduction: 14,
    absenceDeduction: 0,
    otherDeductions: 0,
    netSalary: 20896,
    status: 'approved',
    paymentMethod: 'تحويل بنكي فوري (البنك الأهلي المصري)',
    notes: 'إجازة سنوية مدفوعة الأجر بالكامل',
    createdAt: '2026-09-22',
  },
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval-admin',
    employeeId: 'emp-admin',
    employeeName: 'محمد زكريا (المدير الإداري ومسؤول الموارد البشرية)',
    department: 'الموارد البشرية والإدارة العليا',
    jobTitle: 'مدير عام الموارد البشرية والشؤون الإدارية (HR Director)',
    period: 'الربع الثالث 2026',
    productivityScore: 98,
    qualityScore: 97,
    punctualityScore: 96,
    teamworkScore: 98,
    innovationScore: 95,
    overallScore: 96.8,
    strengths: 'قيادة مؤسسية بارزة، ضبط الامتثال لقانون العمل المصري وقانون التأمينات 148 لسنة 2019، وتحديث الهيكل التنظيمي.',
    areasForImprovement: 'استكمال الربط الآلي الشامل لمنظومة توحيد أسس ومعايير احتساب ضريبة الأجور مع مصلحة الضرائب المصرية.',
    goals: 'ميكنة دورة استمارات التأمينات (س1 وس2 وس6) رقمياً بنسبة 100% بنهاية العام.',
    aiSummary: 'أداء قيادي استراتيجي متميز؛ ساهم مباشرة في ضبط منظومة الموارد البشرية والامتثال القانوني الكامل لمعايير وزارة العمل وهيئة التأمينات الاجتماعية المصرية.',
    evaluatorName: 'مجلس الإدارة (Board of Directors)',
    status: 'finalized',
    createdAt: '2026-09-18',
  },
  {
    id: 'eval-1',
    employeeId: 'emp-1',
    employeeName: 'م. أحمد محمود الشناوي',
    department: 'الهندسة والتقنية',
    jobTitle: 'كبير مهندسي البرمجيات والنظم السحابية',
    period: 'الربع الثالث 2026',
    productivityScore: 95,
    qualityScore: 96,
    punctualityScore: 92,
    teamworkScore: 94,
    innovationScore: 98,
    overallScore: 95,
    strengths: 'كفاءة هندسية فائقة، قيادة فرق التطوير، والمبادرة في بناء أنظمة سحابية سريعة ومستقرة.',
    areasForImprovement: 'تفويض بعض المهام البرمجية الروتينية للمطورين الصاعدين لتوفير الوقت للمشاريع الاستراتيجية.',
    goals: 'قيادة إطلاق منصة الخدمات الرقمية الجديدة وتدريب الفريق الهندسي.',
    aiSummary: 'أداء تقني استثنائي يتجاوز التوقعات؛ أسهم مباشرة في استقرار البنية التحتية وتسريع عمليات التسليم البرمجي بنسبة 35%.',
    evaluatorName: 'د. طارق المنياوي (الرئيس التنفيذي للتكنولوجيا)',
    status: 'finalized',
    createdAt: '2026-09-19',
  },
];

export const INITIAL_TASKS: HRTask[] = [
  {
    id: 'task-1',
    title: 'إيداع مسيرات رواتب سبتمبر بالبنك ومطابقة استقطاعات التأمينات (قانون 148 لسنة 2019)',
    description: 'التأكد من خصم حصة العامل 11% وحصة الشركة 18.75% وتجهيز ملف البنك CIB والأهلي.',
    assignedTo: 'محمد زكريا',
    dueDate: '2026-09-26',
    priority: 'urgent',
    status: 'in_progress',
    syncedWithGoogle: true,
    createdAt: '2026-09-20',
  },
  {
    id: 'task-2',
    title: 'تجهيز وتقديم استمارة (1) تأمينات اجتماعية للموظفين الجدد بمكتب التأمينات التابع',
    description: 'استيفاء بيانات الرقم القومي والأجر التأميني الشامل وتقديم س1 قبل انقضاء مهلة الشهر.',
    assignedTo: 'سارة الصاوي',
    dueDate: '2026-09-28',
    priority: 'high',
    status: 'pending',
    syncedWithGoogle: true,
    createdAt: '2026-09-22',
  },
  {
    id: 'task-3',
    title: 'مراجعة الحد الأدنى للأجور (6,000 ج.م) لجميع عقود العمل بالشركة وفقاً لقرارات المجلس القومي للأجور',
    description: 'التأكد من التزام جميع الرواتب الأساسية والبدلات بحد الكفاية القانوني في مصر.',
    assignedTo: 'محمد زكريا',
    dueDate: '2026-09-30',
    priority: 'high',
    status: 'completed',
    syncedWithGoogle: true,
    createdAt: '2026-09-15',
  },
  {
    id: 'task-4',
    title: 'تجديد وثيقة التأمين الصحي الشامل والكشف الطبي الدوري للعاملين بالتعاون مع هيئة التأمين الصحي',
    description: 'إجراء الفحوصات الطبية الدورية وتجديد بطاقات الرعاية الصحية للموظفين.',
    assignedTo: 'سارة الصاوي',
    dueDate: '2026-10-05',
    priority: 'medium',
    status: 'pending',
    syncedWithGoogle: false,
    createdAt: '2026-09-21',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'اعتماد مسير رواتب سبتمبر 2026 بالجنيه المصري',
    message: 'تم إعداد واعتماد مسير رواتب شهر سبتمبر بإجمالي 156,086.00 ج.م مع مطابقة حصص التأمينات الاجتماعية والضرائب.',
    type: 'payroll',
    read: false,
    createdAt: 'قبل 25 دقيقة',
  },
  {
    id: 'notif-2',
    title: 'طلب إجازة عارضة جديد قيد الانتظار',
    message: 'قدم الموظف عبد الرحمن الألفي طلب إجازة عارضة لمدة يومين طبقاً للمادة 48 من قانون العمل.',
    type: 'leave',
    read: false,
    createdAt: 'قبل ساعة ونصف',
  },
  {
    id: 'notif-3',
    title: 'توليد قيد اليومية المحاسبي وفقاً لدليل الحسابات المصري',
    message: 'تم توليد قيد استحقاق المرتبات المتوازن وترحيله وجاهز للمزامنة مع نظام الحسابات (دفترة / قيود / كويك بوكس).',
    type: 'info',
    read: true,
    createdAt: 'اليوم، 10:00 ص',
  },
  {
    id: 'notif-4',
    title: 'الامتثال لقانون العمل المصري 12 لسنة 2003',
    message: 'تم فحص ومطابقة جميع سجلات الحضور والإجازات وعقود العمل مع قانون العمل والتأمينات بنسبة 100%.',
    type: 'success',
    read: true,
    createdAt: 'أمس',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    action: 'تسجيل دخول موثق عبر Google',
    performedBy: 'محمد زكريا (المدير الإداري)',
    details: 'تسجيل دخول ناجح بحساب mz0970mmz@gmail.com المعتمد بقاعدة بيانات موظفي الشركة.',
    createdAt: '2026-09-24 08:00:15',
  },
  {
    id: 'log-2',
    action: 'اعتماد مسير الرواتب الشهرية',
    performedBy: 'محمد زكريا (مدير الموارد البشرية)',
    details: 'اعتماد مسير رواتب شهر سبتمبر 2026 لعدد 6 موظفين بالجنيه المصري EGP.',
    createdAt: '2026-09-23 14:30:00',
  },
  {
    id: 'log-3',
    action: 'اعتماد إجازة سنوية',
    performedBy: 'سارة الصاوي (أخصائية علاقات العمل)',
    details: 'الموافقة على طلب الإجازة السنوية للموظف كريم الجوهري طبقاً للمادة 47 من قانون العمل.',
    createdAt: '2026-09-20 11:15:22',
  },
  {
    id: 'log-4',
    action: 'مزامنة مهام الموارد البشرية مع Google Tasks',
    performedBy: 'النظام الآلي (Integration Agent)',
    details: 'مزامنة 4 مهام عاجلة تتضمن ملفات التأمينات مع حساب Google Tasks بنجاح.',
    createdAt: '2026-09-22 09:00:00',
  },
];

export const INITIAL_JOURNAL_ENTRIES: AccountingJournalEntry[] = [
  {
    id: 'je-1',
    referenceNo: 'JV-2026-09-PAY-EG',
    date: '2026-09-25',
    description: 'إثبات استحقاق مسير مرتبات وأجور العاملين لشهر سبتمبر 2026 بالجنيه المصري',
    system: 'daftra',
    status: 'draft',
    totalDebit: 182750,
    totalCredit: 182750,
    lines: [
      {
        accountCode: '510101',
        accountName: 'مصروف المرتبات والأجور الأساسية (Basic Salaries)',
        debit: 156000,
        credit: 0,
        description: 'إجمالي المرتبات الأساسية لشهر سبتمبر بالجنيه المصري',
      },
      {
        accountCode: '510102',
        accountName: 'مصروف بدلات السكن والانتقال (Allowances Expense)',
        debit: 21500,
        credit: 0,
        description: 'إجمالي بدلات السكن والانتقال لكافة العاملين بالمنشأة',
      },
      {
        accountCode: '510103',
        accountName: 'مصروف ساعات العمل الإضافي والحوافز (Overtime & Bonuses)',
        debit: 5250,
        credit: 0,
        description: 'أجر ساعات العمل الإضافي وحوافز الإنتاج المعتمدة',
      },
      {
        accountCode: '210101',
        accountName: 'أرصدة مرتبات مستحقة للعاملين (Accrued Salaries Payable - CIB/NBE)',
        debit: 0,
        credit: 156086,
        description: 'صافي المرتبات واجبة التحويل للحسابات البنكية للموظفين (ج.م)',
      },
      {
        accountCode: '210201',
        accountName: 'الهيئة القومية للتأمين الاجتماعي - اشتراكات مستحقة (Social Insurance Payable)',
        debit: 0,
        credit: 11990,
        description: 'اشتراكات التأمينات الاجتماعية (حصة العامل 11% + حصة المنشأة 18.75% قانون 148)',
      },
      {
        accountCode: '210301',
        accountName: 'مصلحة الضرائب المصرية - ضريبة المرتبات وما في حكمها (Payroll Tax Payable)',
        debit: 0,
        credit: 14674,
        description: 'مستحقات ضريبة كسب العمل المستقطعة لتوريدها للمصلحة',
      },
    ],
  },
];

export const DEFAULT_BRANDING: CompanyBranding = {
  companyName: 'شركة النيل للحلول والتطوير (ش.م.م)',
  subtitle: 'منظومة إدارة الموارد البشرية والرواتب - جمهورية مصر العربية',
  logoUrl: '',
  taxNumber: '100-293-847',
  commercialRecord: '194820',
  address: 'التجمع الخامس - القاهرة الجديدة، جمهورية مصر العربية',
  updatedAt: new Date().toISOString(),
  updatedBy: 'mz0970mmz@gmail.com',
};

export const INITIAL_CHAT_GROUPS: ChatGroup[] = [
  {
    id: 'grp-all',
    name: '📢 التعميمات العامة للشركة',
    description: 'المجموعة العامة لكافة العاملين بالشركة للإعلانات والقرارات الرسمية',
    department: 'all',
    icon: 'Megaphone',
    createdAt: '2026-01-01',
  },
  {
    id: 'grp-tech',
    name: '💻 فريق الهندسة والتقنية',
    description: 'قناة التواصل اليومية والمهام التقنية لمهندسي البرمجيات والنظم',
    department: 'الهندسة والتقنية',
    icon: 'Code',
    isDepartmentOnly: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'grp-hr',
    name: '👥 الموارد البشرية والإدارة العليا',
    description: 'مناقشات سياسات العمل والتوظيف والتأمينات الاجتماعية',
    department: 'الموارد البشرية والإدارة العليا',
    icon: 'Users',
    isDepartmentOnly: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'grp-fin',
    name: '💰 المالية والمحاسبة',
    description: 'متابعة مسيرات الرواتب والميزانيات والضرائب وقيود اليومية',
    department: 'المالية والمحاسبة',
    icon: 'DollarSign',
    isDepartmentOnly: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'grp-mkt',
    name: '📈 التسويق والمبيعات',
    description: 'تنسيق الحملات والمبيعات ومتابعة العملاء',
    department: 'التسويق والمبيعات',
    icon: 'TrendingUp',
    isDepartmentOnly: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'grp-ops',
    name: '⚙️ العمليات التشغيلية والدعم',
    description: 'التشغيل اليومي والدعم الفني وإدارة المكاتب',
    department: 'العمليات التشغيلية',
    icon: 'Wrench',
    isDepartmentOnly: true,
    createdAt: '2026-01-01',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    groupId: 'grp-all',
    senderId: 'emp-admin',
    senderName: 'محمد زكريا (المدير الإداري)',
    senderEmail: 'mz0970mmz@gmail.com',
    content: 'السلام عليكم ورحمة الله، تم اعتماد مسير رواتب الشهر الحالي وفقاً لقانون العمل المصري وقانون التأمينات 148، ويمكن للجميع الاطلاع على كشوفهم عبر بوابة الموظف الذاتية.',
    timestamp: '09:00 ص',
  },
  {
    id: 'msg-2',
    groupId: 'grp-all',
    senderId: 'emp-1',
    senderName: 'م. أحمد الشناوي',
    senderEmail: 'ahmed.shinawy@company.eg',
    content: 'شكراً جزيلاً أستاذ محمد، تسلم الأيادي وبالتوفيق للجميع.',
    timestamp: '09:15 ص',
  },
  {
    id: 'msg-3',
    groupId: 'grp-tech',
    senderId: 'emp-1',
    senderName: 'م. أحمد الشناوي',
    senderEmail: 'ahmed.shinawy@company.eg',
    content: 'فريق الهندسة: تم إطلاق التحديث السحابي الجديد وتحسين استجابة المنظومة وسرعة التحميل بنسبة 40%.',
    timestamp: '10:00 ص',
  },
  {
    id: 'msg-4',
    groupId: 'grp-hr',
    senderId: 'emp-admin',
    senderName: 'محمد زكريا (المدير الإداري)',
    senderEmail: 'mz0970mmz@gmail.com',
    content: 'يرجى مراجعة نماذج استمارة س1 للموظفين الجدد لتسليمها لمكتب التأمينات هذا الأسبوع.',
    timestamp: '11:30 ص',
  },
];

export const INITIAL_ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: 'req-1',
    fullName: 'يوسف عبد الرحمن حسن',
    email: 'youssef.abdelrahman@company.eg',
    phone: '+20 10 9876 5432',
    nationalId: '29505120101987',
    department: 'الهندسة والتقنية',
    jobTitle: 'مهندس جودة واختبار برمجيات',
    employeeCode: 'EMP-EG-010',
    socialInsuranceNumber: '11983021',
    notes: 'تم توقيع العقد في بداية الشهر وأرغب بالدخول للبوابة لتسجيل الحضور ومتابعة المهام.',
    status: 'pending',
    requestedAt: '2026-09-24',
  },
];


